=== kesara/ginimonara/GiniMonara/GiniMonara/xsd/Categories.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--
Basic Categories Specification
Usage: images/videos
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="categories" type="categoriesType"/>
  <xs:complexType name="categoriesType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="category" type="categoryType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoryType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== kesara/ginimonara/trunk/GiniMonara/GiniMonara/xml/Category.xml
<?xml version="1.0" encoding="utf-8" ?>
<categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://ginimonara.sourceforge.net/Categories.xsd">
  <category name="DublinCore" type="default">Title</category>
  <category name="DublinCore" type="default">Creator</category>
  <category name="DublinCore" type="default">Subject</category>
  <category name="DublinCore" type="default">Description</category>
  <category name="DublinCore" type="default">Publisher</category>
  <category name="DublinCore" type="default">Contributor</category>
  <category name="DublinCore" type="default">Date</category>
  <category name="DublinCore" type="default">Type</category>
  <category name="DublinCore" type="default">Format</category>
  <category name="DublinCore" type="default">Identifier</category>
  <category name="DublinCore" type="default">Source</category>
  <category name="DublinCore" type="default">Language</category>
  <category name="DublinCore" type="default">Relation</category>
  <category name="DublinCore" type="default">Coverage</category>
  <category name="DublinCore" type="default">Rights</category>
  <category name="system" type="hidden">fileName</category>
  <category name="system" type="hidden">mediaType</category>
  <category name="Common" type="default">Tag</category>
  <category name="Common" type="area">Selected Area</category>
  <category name="Video" type="timeframe">Scene</category>
  <category name="Video" type="cube">Selected Scene</category>
</categories>
